### ISSUE TITLE
OverlayManager.getLanguages called before set-dictionary-location

### ISSUE THREAD

**Issue by Biserkov** [rschroll/lt-spelling#8]
In user.behaviours

```clojure
 [:app :lt.plugins.spelling/set-dictionary-location "/Program Files (x86)/Mozilla Firefox/dictionaries"]
 [:editor.markdown :lt.plugins.spelling/enable]
```
The spell-checkers works, but the following error appears in the console

```
Error: ENOENT, no such file or directory 'C:\usr\share\hunspell'
    at Object.fs.readdirSync (fs.js:654:18)
    at Object.OverlayManager.getLanguages (C:\Users\me\AppData\Local\LightTable\plugins\Spelling\js\overlays.js:79:20)
    at eval (C:\Users\me\AppData\Local\LightTable\plugins\Spelling\spelling_compiled.js:106:253)
    at lt.objs.sidebar.command.__GT_items (file:///C:/bin/LightTable/core/node_modules/lighttable/bootstrap.js:25462:339)
```

**Comment by rschroll** [comment]
I've fixed the immediate error, and that error message is now trapped 
and handled appropriately.  I couldn't reproduce the problem of it 
looking in the wrong directory, though.  This may be due to the other 
changes I've made in how defaults are handled.

I've uploaded a new version with the changes, and hopefully it'll make 
it into the plugin repository soon.  Once it does, could you give it a 
try and see if this problem still exists?

Thanks!

**Comment by Biserkov** [comment]
The plugin manager still shows version 0.0.4 as the latest.

I installed the plugin locally by cloning the repo to ~/AppData/Local/LightTable/plugins

The error no longer appears.

**Comment by rschroll** [comment]
Yeah, they've replaced the automatic updater that was built right into 
LightTable with a manual one involving GitHub issues.  Progress?

Thanks for checking it out!
